/**
 * Author:  Giulio Tognetto
 * Created: 2 apr 2026
 */
CREATE TABLE CLIENTI (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PREFERENZE VARCHAR(500)
);

CREATE TABLE PACCHETTI (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITOLO VARCHAR(150) NOT NULL,
    DESCRIZIONE VARCHAR(500),
    TAGS VARCHAR(255),
    PREZZO DOUBLE NOT NULL,
    IS_OFFERTA BOOLEAN DEFAULT FALSE,
    IMMAGINE VARCHAR(512)
);

CREATE TABLE SERVIZI (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_PACCHETTO INTEGER NOT NULL,
    TIPO VARCHAR(100),
    NOME VARCHAR(100) NOT NULL,
    PREZZO DOUBLE DEFAULT 0.0,
    DESCRIZIONE VARCHAR(255),
    IMMAGINE VARCHAR(512),
    CONSTRAINT FK_PACCHETTO_SERVIZIO FOREIGN KEY (ID_PACCHETTO) REFERENCES PACCHETTI(ID) ON DELETE CASCADE
);

CREATE TABLE PRENOTAZIONI (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_CLIENTE INTEGER NOT NULL,
    ID_PACCHETTO INTEGER NOT NULL,
    DATA_PRENOTAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PREZZO_PAGATO DOUBLE NOT NULL,
    STATO VARCHAR(255) DEFAULT 'PENDENTE',
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTI(ID),
    CONSTRAINT FK_PACCHETTO_PREN FOREIGN KEY (ID_PACCHETTO) REFERENCES PACCHETTI(ID)
);