package com.agenziaviaggi.app;

/**
 *
 * @author Giulio Tognetto
 */
public class AgenziaViaggiApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgenziaViaggiApp.class.getName());

    /**
     * Creates new form MainFrame
     */
    public AgenziaViaggiApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pacchetti = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        labelListaPacchetti = new javax.swing.JLabel();
        offertaCheckboxPacchetto = new java.awt.Checkbox();
        prezzoSpinnerPacchetto = new javax.swing.JSpinner();
        labelTitoloPacchetto = new javax.swing.JLabel();
        labelEditPacchetto = new javax.swing.JLabel();
        labelTagsPacchetto = new javax.swing.JLabel();
        labelPrezzoPacchetto = new javax.swing.JLabel();
        labelDescrizionePacchetto = new javax.swing.JLabel();
        labelURLImmaginePacchetto = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        textField4 = new java.awt.TextField();
        tagsTextField = new javax.swing.JTextField();
        titoloTextField = new javax.swing.JTextField();
        immagineTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descrizioneTextArea = new javax.swing.JTextArea();
        addPacchetto = new javax.swing.JButton();
        removePacchetto = new javax.swing.JButton();
        clearPacchetto = new javax.swing.JButton();
        servizi = new java.awt.Panel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        servizioComboBox = new javax.swing.JComboBox<>();
        tipoServizioTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        prezzoServizioSpinner = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        servizioImmagineTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        descrizioneServizioTextArea = new javax.swing.JTextArea();
        clearServizio = new javax.swing.JButton();
        removeServizio = new javax.swing.JButton();
        addServizio = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        prenotazioni = new java.awt.Panel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        statoPrenotazione = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        prenotazioniEsistenti = new javax.swing.JList<>();
        clearPrenotazione = new javax.swing.JButton();
        removePrenotazione = new javax.swing.JButton();
        addPrenotazione = new javax.swing.JButton();
        prenotazioneCliente = new javax.swing.JComboBox<>();
        prenotazionePacchetto = new javax.swing.JComboBox<>();
        clienti = new java.awt.Panel();
        jScrollPane5 = new javax.swing.JScrollPane();
        clientiEsistenti = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        emailCliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        clearCliente = new javax.swing.JButton();
        removeCliente = new javax.swing.JButton();
        addCliente = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        preferenzeCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        labelListaPacchetti.setLabelFor(jList1);
        labelListaPacchetti.setText("Pacchetti esistenti");

        offertaCheckboxPacchetto.setLabel("Offerta");

        labelTitoloPacchetto.setText("Titolo");

        labelEditPacchetto.setText("Nuovo / Modifica pacchetto");

        labelTagsPacchetto.setText("Tags");

        labelPrezzoPacchetto.setText("Prezzo");

        labelDescrizionePacchetto.setText("Descrizione");

        labelURLImmaginePacchetto.setText("URL Immagine");

        textField4.setText("textField4");

        tagsTextField.setToolTipText("Inserisci i tag del pacchetto separati da virgola");

        titoloTextField.setToolTipText("Inserisci il titolo del pacchetto qui");

        immagineTextField.setToolTipText("Inserisci l'URL dell'immagine del pacchetto qui");

        descrizioneTextArea.setColumns(20);
        descrizioneTextArea.setRows(5);
        descrizioneTextArea.setToolTipText("Inserisci la descrizione del pacchetto qui");
        jScrollPane3.setViewportView(descrizioneTextArea);

        addPacchetto.setText("Add");

        removePacchetto.setText("Remove");

        clearPacchetto.setText("Clear");

        javax.swing.GroupLayout pacchettiLayout = new javax.swing.GroupLayout(pacchetti);
        pacchetti.setLayout(pacchettiLayout);
        pacchettiLayout.setHorizontalGroup(
            pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pacchettiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pacchettiLayout.createSequentialGroup()
                        .addComponent(clearPacchetto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removePacchetto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPacchetto))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(pacchettiLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pacchettiLayout.createSequentialGroup()
                                .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelTagsPacchetto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDescrizionePacchetto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(labelPrezzoPacchetto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTitoloPacchetto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelURLImmaginePacchetto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(37, 37, 37)
                                .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titoloTextField)
                                    .addComponent(offertaCheckboxPacchetto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(immagineTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prezzoSpinnerPacchetto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tagsTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(pacchettiLayout.createSequentialGroup()
                                .addComponent(labelEditPacchetto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelListaPacchetti, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pacchettiLayout.setVerticalGroup(
            pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pacchettiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEditPacchetto, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(labelListaPacchetti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pacchettiLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pacchettiLayout.createSequentialGroup()
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTitoloPacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titoloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTagsPacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPrezzoPacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezzoSpinnerPacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelURLImmaginePacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(immagineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDescrizionePacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offertaCheckboxPacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pacchettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPacchetto)
                            .addComponent(removePacchetto)
                            .addComponent(clearPacchetto)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pacchetti", pacchetti);

        jLabel26.setText("Nuovo / Modifica servizio");

        jLabel27.setText("Servizi esistenti");

        jLabel28.setText("Pacchetto");

        servizioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        servizioComboBox.setToolTipText("Seleziona il pacchetto a cui vuoi modificare i servizi");
        servizioComboBox.addActionListener(this::servizioComboBoxActionPerformed);

        tipoServizioTextField.setEditable(false);
        tipoServizioTextField.setToolTipText("");

        jLabel29.setText("Tipo");

        jLabel30.setText("Nome");

        nomeTextField.setEditable(false);
        nomeTextField.setToolTipText("Inserisci il nome del servizio");

        jLabel31.setText("Prezzo");

        prezzoServizioSpinner.setEnabled(false);

        jLabel32.setText("URL Immagine");

        servizioImmagineTextField.setToolTipText("Inserisci l'URL dell'immagine del pacchetto qui");
        servizioImmagineTextField.setEnabled(false);

        jLabel33.setText("Descrizione");

        descrizioneServizioTextArea.setColumns(20);
        descrizioneServizioTextArea.setRows(5);
        descrizioneServizioTextArea.setEnabled(false);
        jScrollPane7.setViewportView(descrizioneServizioTextArea);

        clearServizio.setText("Clear");

        removeServizio.setText("Remove");

        addServizio.setText("Add");

        jScrollPane8.setViewportView(jList5);

        javax.swing.GroupLayout serviziLayout = new javax.swing.GroupLayout(servizi);
        servizi.setLayout(serviziLayout);
        serviziLayout.setHorizontalGroup(
            serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serviziLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serviziLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serviziLayout.createSequentialGroup()
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(serviziLayout.createSequentialGroup()
                                .addComponent(clearServizio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeServizio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addServizio))
                            .addGroup(serviziLayout.createSequentialGroup()
                                .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                                .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(servizioImmagineTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tipoServizioTextField)
                                    .addComponent(servizioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomeTextField)
                                    .addComponent(prezzoServizioSpinner)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        serviziLayout.setVerticalGroup(
            serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviziLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(serviziLayout.createSequentialGroup()
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servizioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(tipoServizioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeTextField)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prezzoServizioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servizioImmagineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(serviziLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(serviziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addServizio)
                            .addComponent(removeServizio)
                            .addComponent(clearServizio)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Servizi", servizi);

        jLabel18.setText("Nuova / Modifica prenotazione");

        jLabel22.setText("Cliente");

        jLabel23.setText("Pacchetto");

        jLabel24.setText("Stato");

        statoPrenotazione.setEditable(false);
        statoPrenotazione.setToolTipText("Inserisci lo stato della prenotazione");
        statoPrenotazione.addActionListener(this::statoPrenotazioneActionPerformed);

        jLabel25.setText("Prenotazioni esistenti");

        jScrollPane6.setViewportView(prenotazioniEsistenti);

        clearPrenotazione.setText("Clear");

        removePrenotazione.setText("Remove");

        addPrenotazione.setText("Add");

        prenotazioneCliente.setToolTipText("Scegli il cliente che vuole effetturare una prenotazione");

        prenotazionePacchetto.setToolTipText("Scegli il pacchetto da prenotare");

        javax.swing.GroupLayout prenotazioniLayout = new javax.swing.GroupLayout(prenotazioni);
        prenotazioni.setLayout(prenotazioniLayout);
        prenotazioniLayout.setHorizontalGroup(
            prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prenotazioniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prenotazioniLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addGroup(prenotazioniLayout.createSequentialGroup()
                        .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(prenotazioniLayout.createSequentialGroup()
                                .addComponent(clearPrenotazione)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removePrenotazione)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addPrenotazione))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, prenotazioniLayout.createSequentialGroup()
                                .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(statoPrenotazione)
                                    .addComponent(prenotazioneCliente, 0, 421, Short.MAX_VALUE)
                                    .addComponent(prenotazionePacchetto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        prenotazioniLayout.setVerticalGroup(
            prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prenotazioniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(prenotazioniLayout.createSequentialGroup()
                        .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(prenotazioneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenotazionePacchetto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statoPrenotazione)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(prenotazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPrenotazione)
                            .addComponent(removePrenotazione)
                            .addComponent(clearPrenotazione)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prenotazioni", prenotazioni);

        jScrollPane5.setViewportView(clientiEsistenti);

        jLabel16.setText("Clienti esistenti");

        jLabel17.setText("Nuovo / Modifica cliente");

        jLabel19.setText("Nome");

        nomeCliente.setEditable(false);
        nomeCliente.setToolTipText("Inserisci il nome del cliente");

        emailCliente.setEditable(false);
        emailCliente.setToolTipText("Inserisci l'email del cliente");

        jLabel20.setText("Email");

        clearCliente.setText("Clear");

        removeCliente.setText("Remove");

        addCliente.setText("Add");

        jLabel21.setText("Preferenze");

        preferenzeCliente.setEditable(false);
        preferenzeCliente.setToolTipText("Inserisci le preferenze del cliente");

        javax.swing.GroupLayout clientiLayout = new javax.swing.GroupLayout(clienti);
        clienti.setLayout(clientiLayout);
        clientiLayout.setHorizontalGroup(
            clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientiLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(561, 561, 561))
                    .addGroup(clientiLayout.createSequentialGroup()
                        .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(clearCliente)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(clientiLayout.createSequentialGroup()
                                .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(preferenzeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(clientiLayout.createSequentialGroup()
                                .addComponent(removeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCliente)
                                .addGap(9, 9, 9)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clientiLayout.createSequentialGroup()
                    .addContainerGap(526, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(329, 329, 329)))
        );
        clientiLayout.setVerticalGroup(
            clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientiLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(clientiLayout.createSequentialGroup()
                        .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preferenzeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCliente)
                            .addComponent(removeCliente)
                            .addComponent(clearCliente))
                        .addGap(9, 9, 9))))
            .addGroup(clientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clientiLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(368, 368, 368)))
        );

        jTabbedPane1.addTab("Clienti", clienti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statoPrenotazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statoPrenotazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statoPrenotazioneActionPerformed

    private void servizioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servizioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servizioComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgenziaViaggiApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCliente;
    private javax.swing.JButton addPacchetto;
    private javax.swing.JButton addPrenotazione;
    private javax.swing.JButton addServizio;
    private javax.swing.JButton clearCliente;
    private javax.swing.JButton clearPacchetto;
    private javax.swing.JButton clearPrenotazione;
    private javax.swing.JButton clearServizio;
    private java.awt.Panel clienti;
    private javax.swing.JList<String> clientiEsistenti;
    private javax.swing.JTextArea descrizioneServizioTextArea;
    private javax.swing.JTextArea descrizioneTextArea;
    private javax.swing.JTextField emailCliente;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField immagineTextField;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDescrizionePacchetto;
    private javax.swing.JLabel labelEditPacchetto;
    private javax.swing.JLabel labelListaPacchetti;
    private javax.swing.JLabel labelPrezzoPacchetto;
    private javax.swing.JLabel labelTagsPacchetto;
    private javax.swing.JLabel labelTitoloPacchetto;
    private javax.swing.JLabel labelURLImmaginePacchetto;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField nomeTextField;
    private java.awt.Checkbox offertaCheckboxPacchetto;
    private java.awt.Panel pacchetti;
    private javax.swing.JTextField preferenzeCliente;
    private javax.swing.JComboBox<String> prenotazioneCliente;
    private javax.swing.JComboBox<String> prenotazionePacchetto;
    private java.awt.Panel prenotazioni;
    private javax.swing.JList<String> prenotazioniEsistenti;
    private javax.swing.JSpinner prezzoServizioSpinner;
    private javax.swing.JSpinner prezzoSpinnerPacchetto;
    private javax.swing.JButton removeCliente;
    private javax.swing.JButton removePacchetto;
    private javax.swing.JButton removePrenotazione;
    private javax.swing.JButton removeServizio;
    private java.awt.Panel servizi;
    private javax.swing.JComboBox<String> servizioComboBox;
    private javax.swing.JTextField servizioImmagineTextField;
    private javax.swing.JTextField statoPrenotazione;
    private javax.swing.JTextField tagsTextField;
    private java.awt.TextField textField4;
    private javax.swing.JTextField tipoServizioTextField;
    private javax.swing.JTextField titoloTextField;
    // End of variables declaration//GEN-END:variables
}
